config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  mount Sidekiq::Web => '/sidekiq'

  root to: "pages#index"
  namespace :admin do
    resources :orders, only: [:index, :show, :destroy]
  end
  resources :products
  resources :orders, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/order_searchable.rb
module OrderSearchable
  extend ActiveSupport::Concern

  included do
    scope :filter_by_customer_name, ->(customer_name) { 
      where("LOWER(customer_name) LIKE LOWER(?)", "%#{customer_name}%") if customer_name.present? 
    }
  
    scope :filter_by_address, ->(address) { 
      where("LOWER(address) LIKE LOWER(?)", "%#{address}%") if address.present? 
    }
  
    scope :filter_by_zip_code, ->(zip_code) { 
      where(zip_code: zip_code) if zip_code.present? 
    }
  
    scope :filter_by_shipping_method, ->(shipping_method) { 
      where("LOWER(shipping_method) LIKE LOWER(?)", "%#{shipping_method}%") if shipping_method.present? 
    }
  
    scope :filter_by_product_id, ->(product_id) { 
      where(product_id: product_id) if product_id.present? 
    }
  
    scope :filter_by_status, ->(status) { 
      where(status: status) if statuses.include?(status)
    }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include OrderSearchable

  enum status: ['processing'].concat(Fedex::Shipment::STATUS).freeze
  validates :customer_name, :address, :zip_code, :shipping_method, presence: true
  belongs_to :product

  before_create :set_default_status

  scope :not_delivered, -> { where.not(status: 'delivered') }

  def refresh_inventory!
    stock = product.stock
    unless product.update(stock: stock - 1)
      self.errors.add(:product, "out of stock")
      return false
    end
    true
  end

  private

  def set_default_status
    self.status = 'processing'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :price, :stock, presence: true
  validates :stock, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  include PreloadProductsData
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :destroy]
  before_action :set_products, only: [:index]

  def index
    @orders = Orders.search(params)
  end

  def show
    render "orders/show"
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def set_products
    @products = Product.all.order(name: :asc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

  protected

  def authenticate_user!
    unless current_user
      redirect_to new_session_path
    end
  end
end

app/controllers/concerns/preload_products_data.rb
module PreloadProductsData
  extend ActiveSupport::Concern

  private

  def set_products
    @products = Product.all.order(name: :asc)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include PreloadProductsData
  before_action :set_order, :set_products, only: [:show, :destroy]
  before_action :set_products, only: [:new, :edit, :create]

  def show
  end

  def new
    @order = Order.new
  end

  def create
    @order = Orders.create(order_params)
    respond_to do |format|
      if !@order.errors.present?
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:product_id, :customer_name, :address, :zip_code, :shipping_method)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :price, :stock)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Invalid email or password"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def order_statuses_options
    Order.statuses.map { |status| [status.first.humanize, status.first] }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/orders/_search.html.erb
<%= form_with url: admin_orders_path, method: :get, local: true do |f| %>
  <div class="field inline">
    <%= f.label :product_id %><br>
    <%= f.select :product_id, @products.pluck(:name, :id), include_blank: true, selected: params[:product_id] %>
  </div>
  <div class="field inline">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name, value: params[:customer_name] %>
  </div>
  <div class="field inline">
    <%= f.label :address %><br>
    <%= f.text_field :address, value: params[:address] %>
  </div>
  <div class="field inline">
    <%= f.label :zip_code %><br>
    <%= f.number_field :zip_code, value: params[:zip_code] %>
  </div>
  <div class="field inline">
    <%= f.label :shipping_method %><br>
    <%= f.text_field :shipping_method, value: params[:shipping_method] %>
  </div>
  <div class="field inline">
    <%= f.label :status %><br>
    <%= f.select :status, order_statuses_options, include_blank: true, selected: params[:status] %>
  </div>
  <div class="actions inline">
    <%= f.submit "Search" %>
    <%= link_to "Clear", admin_orders_path %>
  </div>
<% end %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<%= render "admin/orders/search" %>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Customer Name</th>
      <th>Address</th>
      <th>Zip Code</th>
      <th>Shipping Method</th>
      <th>Status</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product.name %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.address %></td>
        <td><%= order.zip_code %></td>
        <td><%= order.shipping_method %></td>
        <td><%= order.status %></td>
        <td><%= order.created_at %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Destroy', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CcnCodeChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <ul class="menu">
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "New Order", new_order_path %>
      </li>
      <% if current_user %>
        <li>
          <%= link_to "Listing Orders", admin_orders_path %>
        </li>
        <li>
          <%= link_to "Listing Products", products_path %>
        </li>
        <li>
          <%= link_to 'Log out', session_path(current_user), data: { method: :delete } %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", new_session_path %>
        </li>
      <% end %>
    </ul>
   
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.select :product_id, @products.pluck(:name, :id) %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.number_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :shipping_method %><br>
    <%= f.text_field :shipping_method %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order.product.name %>
</p>


<p>
  <strong>Customer Name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Zip Code:</strong>
  <%= @order.zip_code %>
</p>

<p>
  <strong>Shipping Method:</strong>
  <%= @order.shipping_method %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @order.created_at %>
</p>

<%= link_to 'Home', root_path %>
<%= link_to 'Orders', admin_orders_path if current_user %>

app/views/pages/index.html.erb
<h1>
  HOME - WELCOME!
</h1>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>